version: '3.7'

services:
  server:
    image: vivainnovation-harbor.duckdns.org/wikileaks_backend/wikileaks-dev:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'wikileaks-dev'
    ports:
      - "5002:8000"
      # - "443:7000"
    # entrypoint: /entrypoint.sh
    command: gunicorn --bind :8000 --workers 3 --thread 2 --capture-output --access-logfile /logs/gunicorn-access.log --timeout 300 --env DJANGO_SETTINGS_MODULE=viva_notice.settings viva_notice.wsgi:application
