# Generated by Django 3.2.9 on 2021-11-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notices',
        ),
    ]
