# Generated by Django 3.2.9 on 2021-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
