# Generated by Django 3.2.9 on 2021-11-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
