# Generated by Django 3.2.9 on 2021-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20211209_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
