# Generated by Django 3.2.9 on 2021-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20211116_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='password',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
