# Generated by Django 3.2.9 on 2021-12-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_user_auth_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.notice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.user')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='user_like',
            field=models.ManyToManyField(through='notice.UserLike', to='notice.User'),
        ),
    ]
