# Generated by Django 3.2.9 on 2021-12-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_userlike_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user_like',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.AddField(
            model_name='userlike',
            name='user_ip',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
