# Generated by Django 3.2.9 on 2021-12-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20211209_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.category'),
        ),
    ]
