# Generated by Django 3.2.9 on 2021-12-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20211209_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
