# Generated by Django 3.2.9 on 2021-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20211211_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
